# Site settings
title: "Patrick Andrew Jain-Taylor"
description: "Professional Resume - Inspired by https://github.com/jglovier/resume-template"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Patrick A. Jain-Taylor"
resume_title:                   "Cloud Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "patrick.andrew.taylor@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(508) 565-8116"
resume_contact_address:         "Boston, MA"

resume_header_contact_info:     "Boston, MA • (508) 565-8116 • patrick.andrew.taylor@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Professional Cloud Architect with 8+ years of experience in Information Technology in Financial Services. Skilled in Amazon Web Services, Terraform, Python, and Networking. Strong focus on leadership, team building, and organizational advancement. How can I help?</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_technologies:    true
resume_section_certification:    true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/patrick-andrew-jain-taylor"
  resume_twitter_url:           "https://twitter.com/pjaintaylor"
  resume_linkedin_url:          "https://www.linkedin.com/in/pjaintaylor"
  resume_website_url:           "https://github.com/patrick-andrew-jain-taylor/resume"
  resume_medium_url:            "https://medium.com/@pjaintaylor"
  resume_pdf_url:               "https://github.com/patrick-andrew-jain-taylor/resume/raw/main/webpage/resume.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
