name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: https://resume.patrick.jaintaylor.family
          outputFile: ./webpage/resume.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "A4", "margin": {"left": "2cm", "top": "4cm", "right": "1cm", "bottom": "3.5cm"}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'change: Generate PDF'
          branch: main
          file_pattern: webpage/resume.pdf