name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webpage to PDF
        uses: SetiZ/web_to_pdf_action@master
        with:
          webPageURL: https://resume.patrick.jaintaylor.family
          outputFile: webpage/resume.pdf
          usePuppeteer: true
          pdfOptions: '{"scale": 0.5, "margin": {"top": "0.5in", "bottom": "0.5in"}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'change: Generate PDF'
          branch: main
          file_pattern: webpage/resume.pdf