name: Webpage - Resume
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  webpage-resume-pdf:
    name: Webpage - Resume - PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pdf
      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://resume.patrick.jaintaylor.family
          outputFile: webpage/resume.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'change: Generate PDF'
          branch: pdf
          file_pattern: webpage/resume.pdf
