name: Webpage - Resume
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  webpage-resume-pdf:
    name: Webpage - Resume - PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webpage to PDF
        uses: SetiZ/web_to_pdf_action@master
        with:
          webPageURL: https://resume.patrick.jaintaylor.family
          outputFile: webpage/resume.pdf
          usePuppeteer: true
          pdfOptions: '{"margin": {"top": "0.5in", "bottom": "0.5in"}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'change: Generate PDF'
          branch: main
          file_pattern: webpage/resume.pdf
